
name: micromamba
on:
  push:
  pull_request:
jobs:

  build_simple:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: dev-environment.yaml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'

      - name: setup dependencies
        shell: bash -el {0}
        run: |
          ./build_deps.sh

      - name: build
        shell: bash -el {0}
        run: |
          uv pip install .

      - name: test
        shell: bash -el {0}
        run: |
          pytest -v
